### ISSUE TITLE
variable in template seems not work

### ISSUE THREAD

**Issue by gguan** [mbknor/faster-groovy-templates#10]
I want to set a variable in a template, for example      #{set index:0 /}, and do something like #{set index: index+1 /}
but the variable seems lost in template.

**Comment by mbknor** [comment]
I can confirm that using #{set index:0 /} like that does not work. I will fix it asap.

Doing it like this does work:
#{set 'moreScripts'}
xyz
#{/set}

**Comment by gguan** [comment]
yea, I can actually use %{}% to get it done... the variables in %{}% works perfect

**Comment by mbknor** [comment]
the problem is that the value with name 'index' is not being made available in groovy scope.. I'm looking into it.

**Comment by gguan** [comment]
yea, anyway, thank you for the great work!

**Comment by mbknor** [comment]
This should now be fixed.. releasing 1.1 soon
