### ISSUE TITLE
[bug] error rendering toString() method on a HashMap<String, Object>

### ISSUE THREAD

**Issue by opensas** [mbknor/faster-groovy-templates#11]
steps to reproduce:

```
package controllers;

import java.util.HashMap;
import java.util.Map;

import play.mvc.Controller;

public class Application extends Controller {

    public static void index() {
        Map<String, Object> user = new HashMap<String, Object>();
        user.put("name", "opensas");
        render(user);
    }

}
```

and in the view

```
#{extends 'main.html' /}
#{set title:'Home' /}

Current result:
user.toString() = ${user.toString()}

<hr />
Without fastergt:
user.toString() = [name=opensas]

<hr />
With fastergt:
user.toString() = {name=sas}
```

saludos

sas

**Comment by mbknor** [comment]
I think this problem is related to the following groovy issues:

http://jira.codehaus.org/browse/GROOVY-3612
http://jira.codehaus.org/browse/GROOVY-3236

I have not concluded and are researching more.

**Comment by opensas** [comment]
yeap, it sounds like that's what's happening...

when you have some time (I know you must be pretty busy with play 2.0) you
could build a test project, so that we can add a test for each of these
issues... it would be easier to report and document this kind of stuff, and
to prevent them from coming back in future releases..

saludos

sas

On Fri, Feb 17, 2012 at 7:16 AM, Morten Kjetland <
reply@reply.github.com
