### ISSUE TITLE
Calling ExecutableTemplate.getProperty(String) not working

### ISSUE THREAD

**Issue by tazmaniax** [mbknor/faster-groovy-templates#14]
Hi Morten,

I have a custom Java tag that needs to introspect the parameters bound to the template, yet when I call template.getProperty(String propertyName) the bound variable is not returned and there is no exception in the log.  I tried to debug but I lost track of the thread:

GTLegacyFastTagResolver1X$1(Script).getProperty(String) line: 54  
GTLegacyFastTagResolver1X$1(GroovyTemplate$ExecutableTemplate).getProperty(String) line: 334    

Should this still work as I expect? This is a bit of a show stopper for me.

cheers,
Chris

**Comment by mbknor** [comment]
Can you try with the current version from github?

**Comment by mbknor** [comment]
You might consider using the new fasttags. faster when rendering content.

See here for example: https://github.com/mbknor/gt-engine/blob/master/src/main/java/play/template2/compile/GTInternalFastTags.java

extend GTFastTag and prefix tag-method with "tag_" instead of "_" - See example file for method signature.

**Comment by tazmaniax** [comment]
Yes will try it now. I did try extending GTFastTag but didn't realise I had to rename the method signature so reverted. I will try that as well.

**Comment by tazmaniax** [comment]
The latest code is working and I have changed my tag to extend GTFastTag and that's also working. Thanks for your help. When do you think you will publish these changes?

**Comment by mbknor** [comment]
I'll try to release new version soon - maybe this weekend
