### ISSUE TITLE
Poor performance when NOT in Prod mode

### ISSUE THREAD

**Issue by chris03** [mbknor/faster-groovy-templates#24]
Hi,

in Prod mode the pages render in around 30ms, which is fine, but in DEV mode, rendering a page uses 100% of my CPU and can take easily up to 5 seconds. With the standard template engine it takes a few miliseconds.

My other modules are:
    - play -> secure
    - play -> crud
    - play -> press 1.0.36

I tired without press, the page rendering time went down to around 2 seconds... still slow.

I was just wondering if this is normal ? and what could be done to fix the issue..if this is an issue.

It's not quite productive to have to wait 5 secs for each page when developing.

**Comment by mbknor** [comment]
That sounds really strange!
When I was benchmarking it against the default impl, everything was faster: both compiling and runtime - both in prod- and dev-mode.

The only difference in dev- and prod-mode is that it checks if the template-source files is modified before it renders it.

Can you please supply me with sample project showing this performance problem?
