### ISSUE TITLE
<fieldset> start tag is rendered to late

### ISSUE THREAD

**Issue by zapodot** [mbknor/faster-groovy-templates#5]
When using the <fieldset> tag within a #{form} tag the <fieldset> start tag is rendered to late in the HTML output. Example: An example can be found at https://github.com/zapodot/faster-groovy-templates/blob/testtemplates/samples/sample-app/app/views/UserInput/handleInput.html

With the "old" Play 1.2.X template engine the <fieldset> tag is rendered right after the <form> tag. With the "faster-groovy-templates" module endabled it is rendered after the input[type=text] fields but before the input[type=submit] tag.

I can make a pull request for this one if you'd like

**Comment by mbknor** [comment]
Thanks for finding this issue. In my own custom gt-engine-play-version-branch, I had changed the JavaExtension-file to this:

```
public static String toString(Closure closure) {
    if (closure instanceof GTContentRendererFakeClosure) {
        return ((GTContentRendererFakeClosure)closure).renderToString();
    } else {
        PrintWriter oldWriter = (PrintWriter) closure.getProperty("out");
        StringWriter newWriter = new StringWriter();
        closure.setProperty("out", new PrintWriter(newWriter));
        closure.call();
        closure.setProperty("out", oldWriter);
        return newWriter.toString();
    }
}
```

With the special "if (closure instanceof GTContentRendererFakeClosure)".

This is not possible in this module since I cannot modify an internal Play class.

I'll have to figure out a way.

**Comment by mbknor** [comment]
fixed in commit https://github.com/mbknor/faster-groovy-templates/commit/d9ef9850a6c3a33af27b39e6fd546b30e5bad80e

**Comment by zapodot** [comment]
I can confirm that your fix solved my issue.
