### ISSUE TITLE
#{include '' /} doesn't seem to work

### ISSUE THREAD

**Issue by mak0t0san** [mbknor/faster-groovy-templates#9]
When using the include tag, it doesn't seem to work.

I was able to get around this by creating a tag and using this syntax however:
# {someTag}

**Comment by mbknor** [comment]
I need more info, because the #{include 'pathToFile'/} does work.

There must be something special in your case causing the problem.

Can you provide more info or give me a simple test app showing the problem?

**Comment by mak0t0san** [comment]
You're right, I just wasn't including the path properly. Sorry.

**Comment by mbknor** [comment]
no problem. Thanks for reporting back
